### ISSUE TITLE
Is downloading dataset necessary for sample prediction videos?

### ISSUE THREAD

**Issue by NagabhushanSN95** [alexlee-gk/video_prediction#28]
In your doc, the first step when using a pretrained model is to download the dataset and preprocess it. Is this step really necessary? Is it possible to circumvent it? Because dataset is huge!

**Comment by NagabhushanSN95** [comment]
I tried skipping this step. I got the below error

`CUDA_VISIBLE_DEVICES=0 python scripts/generate.py --input_dir data/bair   --dataset_hparams sequence_length=30   --checkpoint pretrained_models/bair_action_free/ours_savp   --mode test   --results_dir results_test_samples/bair_action_free
loading options from checkpoint pretrained_models/bair_action_free/ours_savp
----------------------------------- Options ------------------------------------
batch_size = 8
checkpoint = pretrained_models/bair_action_free/ours_savp
dataset = softmotion
dataset_hparams = sequence_length=30
fps = 4
gif_length = None
gpu_mem_frac = 0
input_dir = data/bair
mode = test
model = savp
model_hparams = None
num_epochs = 1
num_samples = None
num_stochastic_samples = 5
output_gif_dir = results_test_samples/bair_action_free/ours_savp
output_png_dir = results_test_samples/bair_action_free/ours_savp
results_dir = results_test_samples/bair_action_free
results_gif_dir = results_test_samples/bair_action_free
results_png_dir = results_test_samples/bair_action_free
seed = 7
------------------------------------- End --------------------------------------
Traceback (most recent call last):
  File "scripts/generate.py", line 193, in <module>
    main()
  File "scripts/generate.py", line 105, in main
    hparams=args.dataset_hparams)
  File ".../Stochastic_Adversarial_Video_Prediction/video_prediction/video_prediction/datasets/softmotion_dataset.py", line 16, in __init__
    super(SoftmotionVideoDataset, self).__init__(*args, **kwargs)
  File ".../Stochastic_Adversarial_Video_Prediction/video_prediction/video_prediction/datasets/base_dataset.py", line 242, in __init__
    super(VideoDataset, self).__init__(*args, **kwargs)
  File ".../Stochastic_Adversarial_Video_Prediction/video_prediction/video_prediction/datasets/base_dataset.py", line 40, in __init__
    raise FileNotFoundError("input_dir %s does not exist" % self.input_dir)
FileNotFoundError: input_dir data/bair does not exist`
