### ISSUE TITLE
Error in downloading dataset (partially downloaded)

### ISSUE THREAD

**Issue by NagabhushanSN95** [alexlee-gk/video_prediction#29]
I'm trying to get some sample prediction videos. As per the README, I tried dowloading the dataset. I think it downloaded partially (Total download size is 883.5MB). The output is as follows:

`$bash data/download_and_preprocess_dataset.sh bair`
Downloading 'bair' dataset (this takes a while)
--2019-05-10 18:31:25--  http://rail.eecs.berkeley.edu/datasets/bair_robot_pushing_dataset_v0.tar
Resolving rail.eecs.berkeley.edu (rail.eecs.berkeley.edu)... 128.32.189.73
Connecting to rail.eecs.berkeley.edu (rail.eecs.berkeley.edu)|128.32.189.73|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 32274964480 (30G) [application/x-tar]
Saving to: ‘./data/bair/bair_robot_pushing_dataset_v0.tar’

./data/bair/bair_robot_pushing_dataset_v0.tar        1%[>                                                                                                                ] 421.27M   359KB/s    in 17m 29s 

2019-05-10 18:48:55 (411 KB/s) - Connection closed at byte 441737147. Retrying.

--2019-05-10 18:48:56--  (try: 2)  http://rail.eecs.berkeley.edu/datasets/bair_robot_pushing_dataset_v0.tar
Connecting to rail.eecs.berkeley.edu (rail.eecs.berkeley.edu)|128.32.189.73|:80... connected.
HTTP request sent, awaiting response... 416 Requested range not satisfiable

    The file is already fully retrieved; nothing to do.

softmotion30_44k/test/
softmotion30_44k/test/traj_0_to_255.tfrecords
softmotion30_44k/train/
softmotion30_44k/train/traj_9406_to_9661.tfrecords
softmotion30_44k/train/traj_21628_to_21883.tfrecords
tar: Unexpected EOF in archive
tar: rmtlseek not stopped at a record boundary
tar: Error is not recoverable: exiting now

**Comment by NagabhushanSN95** [comment]
I further tried to get sample predictions. As expected, I got error (see below)

`Traceback (most recent call last):
  File ".../lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File ".../lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File ".../lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File ".../lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File ".../lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcudnn.so.7: cannot open shared object file: No such file or directory`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):
  File "scripts/generate.py", line 13, in <module>
    import tensorflow as tf
  File ".../lib/python3.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File ".../lib/python3.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File ".../lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File ".../lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File ".../lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File ".../lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File ".../lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File ".../lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcudnn.so.7: cannot open shared object file: No such file or directory`
